make_dataset:
  test_size: 0.25
  random_state: 9

train_model:
  random_forest:
    n_estimators: 100
    max_depth: 10
  logistic_regression:
    C: 1.0
    max_iter: 100
  svc:
    C: 1.0
    kernel: 'rbf'
  decision_tree:
    max_depth: 5
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
  adaboost:
    n_estimators: 50
    learning_rate: 1.0
  knn:
    n_neighbors: 5
    weights: uniform
  gaussian_nb: {}